//User constants
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const SET_EMAIL_CONFIRM = "SET_EMAIL_CONFIRM";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

//KYC constants
export const SET_KYC_ACCESS_TOKEN = "SET_KYC_ACCESS_TOKEN";
export const SET_KYC_APPLICATION_STATUS = "SET_KYC_APPLICATION_STATUS";

//Token constants
export const SET_TOKEN_BALANCE = "SET_TOKEN_BALANCE";

//Transaction constants
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const SAVE_TRANSACTION = "SAVE_TRANSACTION";
export const FETCH_BONUS_TRANSACTIONS = "FETCH_BONUS_TRANSACTIONS";

//Admin constants
export const SET_USER_TRANSACTIONS = "SET_USER_TRANSACTIONS";
export const SET_USER_BONUS_TRANSACTIONS = "SET_USER_BONUS_TRANSACTIONS";
export const SET_USERS = "FETCH_USERS";
export const SET_USER_KYC_STATUS = "SET_USER_KYC_STATUS";
export const SET_BONUSES = "SET_BONUSES";
export const UPDATE_BONUS = "UPDATE_BONUS";
